### ISSUE TITLE
2.10.0 breaks my Datadog metrics

### ISSUE THREAD

**Issue by slisaasquatch** [DataDog/java-dogstatsd-client#112] opened 2020-05-08 20:33 UTC
So this is how I currently setup my `StatsDClient`:
```java
new NonBlockingStatsDClient("", "localhost", 8125);
```
I just tried updating the version to 2.10.0, and I've tried using the old deprecated constructor and then this:
```java
new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(8125).build();
```
And Datadog metrics stopped showing up if I use either of those. And as soon as I downgraded to 2.9.0, metrics started working again.
So am I doing something wrong? Is there some additional thing I need to do in 2.10.0?
Thanks!

**Comment by truthbk** [comment] 2020-05-13 17:40
@slisaasquatch thanks for reporting this, I will try to reproduce and get back to you.

**Comment by truthbk** [comment] 2020-05-13 19:06
It seems to be working for me, I have verified both build methods with both a unit test and a small standalone app. Can you give us a little more information about your app? Are you setting any client-supported environment variables?

Would it be possible for you to set netcat to listen on a port of your choosing:
```
nc -u -l -p 76543
```

And then send the metrics there, and see if you see any incoming metrics in that port?

```
NonBlockingStatsDClient client = new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(76543).build();

// do client things, for example:
client.gauge("value", 42);
```

and see what comes out on the netcat side. 

Let me know, and I'll try to help fix whatever's broken @slisaasquatch 

Thank you!

**Comment by slisaasquatch** [comment] 2020-05-13 19:41
Thanks for your reply.

I'm not setting environment variables. I'm just using a `datadog.yaml` config file.

Here's the file content if that helps:

```yaml
api_key: "myApiKey"
dd_url: https://app.datadoghq.com
bind_host: localhost
additional_endpoints: {}
tags: []
dogstatsd_non_local_traffic: false
histogram_aggregates:
  - max
  - median
  - avg
  - count
histogram_percentiles:
  - "0.95"
use_dogstatsd: true
log_level: INFO
logs_enabled: true
process_config:
  enabled: "true"
  intervals: {}
  blacklist_patterns: []
  process_dd_url: https://process.datadoghq.com
log_file: /var/log/datadog/agent.log
log_to_syslog: false
apm_config:
  enabled: true
  apm_non_local_traffic: false
```

I'll try upgrading to 2.10.0 and then run netcat and see how it goes. In the meantime if there's any specific info you are looking for, please let me know.

**Comment by slisaasquatch** [comment] 2020-05-13 21:25
So looks like this code will throw an exception:
```java
new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(76543).build();
```
Stack trace:
```
Exception in thread "main" com.timgroup.statsd.StatsDClientException: Failed to lookup StatsD host
	at com.timgroup.statsd.NonBlockingStatsDClientBuilder.staticStatsDAddressResolution(NonBlockingStatsDClientBuilder.java:224)
	at com.timgroup.statsd.NonBlockingStatsDClientBuilder.build(NonBlockingStatsDClientBuilder.java:154)
	at Test.main(Test.java:33)
Caused by: java.lang.IllegalArgumentException: port out of range:76543
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188)
	at com.timgroup.statsd.NonBlockingStatsDClientBuilder$1.call(NonBlockingStatsDClientBuilder.java:190)
	at com.timgroup.statsd.NonBlockingStatsDClientBuilder$1.call(NonBlockingStatsDClientBuilder.java:185)
	at com.timgroup.statsd.NonBlockingStatsDClientBuilder.staticAddressResolution(NonBlockingStatsDClientBuilder.java:206)
	at com.timgroup.statsd.NonBlockingStatsDClientBuilder.staticStatsDAddressResolution(NonBlockingStatsDClientBuilder.java:222)
	... 2 more
```

**Comment by slisaasquatch** [comment] 2020-05-13 21:52
OK so here's what I did.

I have the existing StatsDClient like this:
```java
StatsDClient statsd = new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(8125).build();
```

And I created another StatsDClient like this:
```java
StatsDClient statsd2 = new NonBlockingStatsDClientBuilder().prefix("").hostname("localhost").port(7654).build();
```

And I have this running every 5 seconds:
```java
statsd2.increment("foo");
```

And I installed netcat and ran `nc -u -l -p 7654`, and nothing is showing up.

**Comment by slisaasquatch** [comment] 2020-05-13 22:23
And again, I downgraded to 2.9.0 with this constructor:
```java
new NonBlockingStatsDClient("", "localhost", 8125);
```
And everything started working again.

**Comment by dwunsch** [comment] 2020-05-14 11:05
just to add another data point - sadly, i don't have time to debug this any further:

when i switched from 2.9.0 to 2.10.0 and changed from
```new NonBlockingStatsDClient("my-application", "localhost", 8125)```
to
```new NonBlockingStatsDClientBuilder().prefix("my-application").hostname("localhost").port(8125).build()```
metrics stopped appearing in datadog.

i guess this is the exact same problem.

**Comment by slisaasquatch** [comment] 2020-05-14 17:38
Glad to see I'm not alone.

**Comment by truthbk** [comment] 2020-05-15 16:14
@slisaasquatch thanks for providing the feedback, I will dig into this over the next couple of days, I'll try to reproduce and come back with a fix. Thanks for doing that for us.

Also @dwunsch sorry for the inconvenience as well. Please stay tuned for updated!

Thanks!

**Comment by truthbk** [comment] 2020-05-15 20:06
Big question I forgot asking @slisaasquatch @dwunsch: what JVM environment are you guys running? And what platform (windows, linux, etc)? Thanks.

**Comment by slisaasquatch** [comment] 2020-05-15 20:17
I'm running Java 8 on GCP Container-Optimized OS.

**Comment by pbarsotti-glovo** [comment] 2020-05-16 17:32
Same problem here. The version published in the public repo under 2.10.0 doesn't work, but if I download the code and build the library locally works just fine.

**Comment by truthbk** [comment] 2020-05-19 22:07
@pbarsotti-glovo, oh that's interesting! What JDK/JVM are you targeting with your local build? 

I'm still struggling to reproduce this myself.

**Comment by pbarsotti-glovo** [comment] 2020-05-20 07:42
@truthbk I did this test on my local computer (macOS Catalina 10.15.4) with this Java setup:

```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

Our services run on Amazon Linux 2, but I didn't tried to use the version compiled locally on them.
If you need more information or help to try a different setup, feel free to ask.

**Comment by truthbk** [comment] 2020-05-23 01:41
OK, I've finally been able to reproduce! Now I can finally work on the fix. Thank you all for all your help. And thank you for the tip @pbarsotti-glovo that stuff was key to help me finally reproduce the problem.

**Comment by jstoja** [comment] 2020-05-25 08:54
@truthbk I confirm that I'm testing on JRE 1.8 and `NonBlockingStatsDClientBuilder` doesn't work but `NonBlockingStatsDClient` does.

**Comment by techied** [comment] 2020-05-26 07:59
Just wanted to leave a +1. I can also reproduce these effects. Metrics are reported correctly from my test rig running JDK 11, but not on prod with JDK 8.

**Comment by truthbk** [comment] 2020-05-26 21:44
`2.10.1` should be available soon. It's been released but it hasn't shown up on maven central just yet. I'm waiting to see if it's an indexing issue or what not. If the fixed lib isn't available tomorrow morning (EST) I will chase it down. 

The issue derived from the fact `2.10.0` was accidentally built atop JDK11 (I had changed the local JDK with jenv to JDK11 and forgot setting it back) and this is what caused the JDK8 problems. The target was `1.7` so I'm still a little surprised. In any case `2.10.1` should now be good. Apologies for the issue.

**Comment by truthbk** [comment] 2020-05-27 18:18
I'll keep this open for a few days, and will close at the end of the week if no more reports come in! Thank you all for your feedback and patience.

**Comment by jstoja** [comment] 2020-05-28 07:41
@truthbk I confirm version 2.10.1 is working as expected with `NonBlockingStatsDClientBuilder`. Thanks for the quick fix!

**Comment by RobMase** [comment] 2020-05-28 07:57
@truthbk thanks for the fix. One more comment: it would be great if you could keep the code examples on the datadog website up to date. It's still referring to version 2.8: https://docs.datadoghq.com/developers/dogstatsd/?tab=java

**Comment by truthbk** [comment] 2020-06-07 17:42
Closing this one! Thank you all!

**Closed by truthbk** 2020-06-07 17:42 UTC
